### ISSUE TITLE
상품 페이지에서 스크롤 바가 나타나는 이슈

### ISSUE THREAD

**Issue by younho9** [woowa-techcamp-2020/bmart-4#70]
## 작업의 크기

> 대략적인 작업의 크기와 난이도를 수치로 표현합니다. ex) 2.5/5 

☕️☕️☕️

## 기타 (스크린샷 등)

> 이슈에 대한 이해를 돕기 위한 자료가 있다면 추가합니다.

![D5D0F78B-CCC4-49FF-86F9-12491B6721F9_1_102_o](https://user-images.githubusercontent.com/48426991/90854392-cf9e4d80-e3b7-11ea-96f9-193950e724a7.jpeg)

**Comment by Pigrabbit** [comment]
해결했습니다
