### ISSUE TITLE
상품 페이지 갔다가 뒤로가기로 홈 돌아오면 네비게이션이 사라집니다.

### ISSUE THREAD

**Issue by atobaum** [woowa-techcamp-2020/bmart-4#74]
## 작업의 크기
상품 페이지 갔다가 뒤로가기로 홈 돌아오면 네비게이션이 사라집니다.
- 브라우저: 크롬

☕️☕️☕️☕️☕️

## 체크리스트

> 이슈에 관련된 요구사항이나 확인해야할 사항이 있으면 추가합니다.

- [ ] 요구사항 1
- [ ] 요구사항 2

## 참고자료

> 해당 이슈를 해결하기 위해 참고해야할 자료가 있다면 추가합니다.

🔗 [링크](URL)

## 기타 (스크린샷 등)
![image](https://user-images.githubusercontent.com/8086328/90856945-0bd4ac80-e3be-11ea-91fa-d159ff2898d6.png)

> 이슈에 대한 이해를 돕기 위한 자료가 있다면 추가합니다.

**Comment by Pigrabbit** [comment]
코드 수정으로 더 이상 버그가 재현되지 않습니다
